In [1]:
%run Perceptron.ipynb

In [2]:
from scipy.io import arff
import urllib.request
import io # for io.StringIO()
import numpy as np
import pandas as pd

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00327/Training%20Dataset.arff"
ftpstream = urllib.request.urlopen(url)
data, meta = arff.loadarff(io.StringIO(ftpstream.read().decode("utf-8")))
num_examples = data.shape[0]
num_features = len(meta.names()) - 1
data = np.array(data.tolist(), dtype=np.int8)
train_examples = round(num_examples*.8)
test_examples = num_examples - train_examples
train_labels = data[:train_examples,30]
test_labels = data[train_examples:,30]
train_data = data[:train_examples,:30]
test_data = data[train_examples:,:30]



In [4]:
PhishingSimplePerceptron = SimplePerceptron(num_features, epochs=100)
PhishingSimplePerceptron.train(train_data, train_labels)

epoch 0 complete with accuracy 0.8995929443690638 .
epoch 1 complete with accuracy 0.9027589326096789 .
epoch 2 complete with accuracy 0.8972184531886025 .
epoch 3 complete with accuracy 0.9045680687471732 .
epoch 4 complete with accuracy 0.9025327905924921 .
epoch 5 complete with accuracy 0.9029850746268657 .
epoch 6 complete with accuracy 0.9003844414292176 .
epoch 7 complete with accuracy 0.9028720036182722 .
epoch 8 complete with accuracy 0.8991406603346902 .
epoch 9 complete with accuracy 0.9006105834464043 .
epoch 10 complete with accuracy 0.9024197195838987 .
epoch 11 complete with accuracy 0.9015151515151515 .
epoch 12 complete with accuracy 0.9026458616010855 .
epoch 13 complete with accuracy 0.9025327905924921 .
epoch 14 complete with accuracy 0.9024197195838987 .
epoch 15 complete with accuracy 0.9009497964721845 .
epoch 16 complete with accuracy 0.9012890094979648 .
epoch 17 complete with accuracy 0.9028720036182722 .
epoch 18 complete with accuracy 0.9062641338760742 .
epo

(array([ 0.04211159, -0.05514874, -0.05500143, -0.00923251,  0.10725265,
         0.26110226,  0.13482931,  0.1523415 , -0.02040735, -0.03312628,
         0.09372731, -0.04077418,  0.02041886,  0.19654084,  0.02423991,
         0.15403483,  0.00852822, -0.02371064, -0.12877797,  0.01559703,
         0.0382853 , -0.01820232, -0.02689553, -0.08607483,  0.00903501,
        -0.0673722 , -0.03205299,  0.10471691,  0.06744032,  0.06156671]),
 0.25175132883157986)

In [5]:
PhishingDynamicPerceptron = DynamicPerceptron(num_features, epochs=100)
PhishingDynamicPerceptron.train(train_data, train_labels)

epoch 0 complete with accuracy 0.8950701040253279 .
epoch 1 complete with accuracy 0.9027589326096789 .
epoch 2 complete with accuracy 0.9044549977385798 .
epoch 3 complete with accuracy 0.9030981456354591 .
epoch 4 complete with accuracy 0.9026458616010855 .
epoch 5 complete with accuracy 0.9015151515151515 .
epoch 6 complete with accuracy 0.9010628674807779 .
epoch 7 complete with accuracy 0.9023066485753053 .
epoch 8 complete with accuracy 0.9029850746268657 .
epoch 9 complete with accuracy 0.9033242876526458 .
epoch 10 complete with accuracy 0.9021935775667119 .
epoch 11 complete with accuracy 0.9021935775667119 .
epoch 12 complete with accuracy 0.9024197195838987 .
epoch 13 complete with accuracy 0.9012890094979648 .
epoch 14 complete with accuracy 0.9010628674807779 .
epoch 15 complete with accuracy 0.9033242876526458 .
epoch 16 complete with accuracy 0.9017412935323383 .
epoch 17 complete with accuracy 0.9010628674807779 .
epoch 18 complete with accuracy 0.9011759384893713 .
epo

(array([ 6.48538650e-04, -4.52063016e-04, -1.50945370e-03, -1.19201170e-04,
         1.52260415e-03,  1.52043724e-01,  2.41863280e-03,  2.55421727e-03,
         1.83383921e-04, -1.16504772e-03,  1.82803246e-03, -1.12701531e-05,
         8.25389819e-05,  3.29096790e-03,  6.60214135e-04,  3.13665685e-03,
         1.81615120e-04, -4.20344300e-04, -1.85414005e-03,  6.04017010e-05,
         5.60786138e-04, -4.60744538e-04, -8.17650260e-05, -1.37307165e-03,
        -6.39286707e-05, -1.16782420e-03, -7.51189855e-04,  1.38614193e-03,
         7.89378551e-04,  1.20829472e-03]), 0.15081607676461362)

In [6]:
PhishingMarginPerceptron = MarginPerceptron(num_features, epochs=100)
PhishingMarginPerceptron.train(train_data, train_labels)

epoch 0 complete with accuracy 0.8955223880597015 .
epoch 1 complete with accuracy 0.8981230212573497 .
epoch 2 complete with accuracy 0.8967661691542289 .
epoch 3 complete with accuracy 0.8914518317503393 .
epoch 4 complete with accuracy 0.8867028493894166 .
epoch 5 complete with accuracy 0.886250565355043 .
epoch 6 complete with accuracy 0.8826322930800543 .
epoch 7 complete with accuracy 0.8793532338308457 .
epoch 8 complete with accuracy 0.8789009497964722 .
epoch 9 complete with accuracy 0.8769787426503844 .
epoch 10 complete with accuracy 0.8768656716417911 .
epoch 11 complete with accuracy 0.8743781094527363 .
epoch 12 complete with accuracy 0.8733604703753958 .
epoch 13 complete with accuracy 0.871438263229308 .
epoch 14 complete with accuracy 0.8688376300316599 .
epoch 15 complete with accuracy 0.8689507010402533 .
epoch 16 complete with accuracy 0.8669154228855721 .
epoch 17 complete with accuracy 0.8660108548168249 .
epoch 18 complete with accuracy 0.8657847127996382 .
epoch

(array([ 0.02360759, -0.01814754, -0.03498522, -0.00121873,  0.05674677,
         0.16551363,  0.0915073 ,  0.08371616, -0.01277552, -0.03590436,
         0.07274561, -0.01743453,  0.01387754,  0.12244672,  0.01704775,
         0.10774079, -0.01314988, -0.01775956, -0.0592598 ,  0.02819168,
         0.02527383, -0.00909882, -0.02453436, -0.04662182, -0.01166414,
        -0.03941702, -0.00645981,  0.03670472,  0.03512701,  0.0366994 ]),
 0.14975631643966042)

In [7]:
PhishingAveragedPerceptron = AveragedPerceptron(num_features, epochs=100)
PhishingAveragedPerceptron.train(train_data, train_labels)

epoch 0 complete with accuracy 0.8962008141112618 .
epoch 1 complete with accuracy 0.9010628674807779 .
epoch 2 complete with accuracy 0.9014020805065581 .
epoch 3 complete with accuracy 0.900497512437811 .
epoch 4 complete with accuracy 0.9028720036182722 .
epoch 5 complete with accuracy 0.9000452284034374 .
epoch 6 complete with accuracy 0.9030981456354591 .
epoch 7 complete with accuracy 0.9014020805065581 .
epoch 8 complete with accuracy 0.8983491632745364 .
epoch 9 complete with accuracy 0.8984622342831298 .
epoch 10 complete with accuracy 0.9026458616010855 .
epoch 11 complete with accuracy 0.9019674355495251 .
epoch 12 complete with accuracy 0.9035504296698327 .
epoch 13 complete with accuracy 0.9046811397557666 .
epoch 14 complete with accuracy 0.904228855721393 .
epoch 15 complete with accuracy 0.9014020805065581 .
epoch 16 complete with accuracy 0.9006105834464043 .
epoch 17 complete with accuracy 0.9023066485753053 .
epoch 18 complete with accuracy 0.899932157394844 .
epoch 

(array([ 0.02655895, -0.02152363, -0.05774166,  0.01859803,  0.10619194,
         0.3161038 ,  0.14384948,  0.13893774, -0.00439552, -0.04223442,
         0.1038592 , -0.0609572 ,  0.02476684,  0.21478166,  0.03761805,
         0.13674235,  0.01910195, -0.03933592, -0.09258248,  0.0277518 ,
         0.04356737, -0.0077137 , -0.01304967, -0.07790613, -0.03640855,
        -0.06356996, -0.01564076,  0.08699977,  0.080052  ,  0.04336932]),
 0.2599245798602143)

In [8]:
PhishingAggressiveMarginPerceptron = AggressiveMarginPerceptron(num_features, epochs=100)
PhishingAggressiveMarginPerceptron.train(train_data, train_labels)

epoch 0 complete with accuracy 0.4245816372682044 .
epoch 1 complete with accuracy 0.4231117141564903 .
epoch 2 complete with accuracy 0.4227725011307101 .
epoch 3 complete with accuracy 0.4226594301221167 .
epoch 4 complete with accuracy 0.4225463591135233 .
epoch 5 complete with accuracy 0.4224332881049299 .
epoch 6 complete with accuracy 0.4224332881049299 .
epoch 7 complete with accuracy 0.4224332881049299 .
epoch 8 complete with accuracy 0.4224332881049299 .
epoch 9 complete with accuracy 0.4224332881049299 .
epoch 10 complete with accuracy 0.4224332881049299 .
epoch 11 complete with accuracy 0.4224332881049299 .
epoch 12 complete with accuracy 0.4224332881049299 .
epoch 13 complete with accuracy 0.4224332881049299 .
epoch 14 complete with accuracy 0.4224332881049299 .
epoch 15 complete with accuracy 0.4224332881049299 .
epoch 16 complete with accuracy 0.4224332881049299 .
epoch 17 complete with accuracy 0.4224332881049299 .
epoch 18 complete with accuracy 0.4224332881049299 .
epo

(array([-2166.1860954 ,  3064.68445265, -3345.10820135, -3690.31633643,
        -3440.13371417,  2731.58131572,  -821.90762944, -3936.09216818,
         2611.26230937, -2936.40756251, -3554.57169858, -3095.12259176,
        -1955.23881584, -1638.18665337,  -359.20845895,  2540.85289503,
        -3041.11079241, -3154.80401951,  -602.00591654, -3736.54448303,
        -4552.43065683, -2854.52512904, -3920.45466395,  -225.46822653,
        -1710.73517496, -3231.05501248,  1788.65825769, -3966.39031942,
        -1882.55731349, -3587.06905939]), -5084.231844904623)

In [9]:
PhishingSimplePerceptron.test(test_data, test_labels)
PhishingDynamicPerceptron.test(test_data, test_labels)
PhishingMarginPerceptron.test(test_data, test_labels)
PhishingAveragedPerceptron.test(test_data, test_labels)
PhishingAggressiveMarginPerceptron.test(test_data, test_labels)

accuracy on test set is 0.9206693803708729 .
accuracy on test set is 0.9200361827227499 .
accuracy on test set is 0.9187697874265038 .
accuracy on test set is 0.9217548620533695 .
accuracy on test set is 0.5379466304839439 .


0.5379466304839439