In [1]:
%run Perceptron.ipynb

In [2]:
from scipy.io import arff
import urllib.request
from io import StringIO()
import numpy as np
import pandas as pd

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00327/Training%20Dataset.arff"
ftpstream = urllib.request.urlopen(url)
data, meta = arff.loadarff(io.StringIO(ftpstream.read().decode("utf-8")))
num_examples = data.shape[0]
num_features = len(meta.names()) - 1
data = np.array(data.tolist(), dtype=np.int8)
np.random.shuffle(data)
train_examples = round(num_examples*.7)
test_examples = ((num_examples - train_examples) // 2)
train_labels = data[:train_examples,30]
dev_labels = data[train_examples:train_examples+test_examples,30]
test_labels = data[train_examples+test_examples:,30]
train_data = data[:train_examples,:30]
dev_data = data[train_examples:train_examples+test_examples,:30]
test_data = data[train_examples+test_examples:,:30]

In [4]:
PhishingSimplePerceptron = SimplePerceptron(num_features, epochs=100)
SimpleWeights = PhishingSimplePerceptron.train(train_data, train_labels, dev_data, dev_labels)[0]

epoch 0 complete with accuracy 0.8972184531886025 .
epoch 1 complete with accuracy 0.9016282225237449 .
epoch 2 complete with accuracy 0.9030981456354591 .
epoch 3 complete with accuracy 0.9021935775667119 .
epoch 4 complete with accuracy 0.9030981456354591 .
epoch 5 complete with accuracy 0.9047942107643601 .
epoch 6 complete with accuracy 0.9041157847127996 .
epoch 7 complete with accuracy 0.8994798733604704 .
epoch 8 complete with accuracy 0.9024197195838987 .
epoch 9 complete with accuracy 0.9041157847127996 .
epoch 10 complete with accuracy 0.9030981456354591 .
epoch 11 complete with accuracy 0.9028720036182722 .
epoch 12 complete with accuracy 0.9008367254635912 .
epoch 13 complete with accuracy 0.9017412935323383 .
epoch 14 complete with accuracy 0.9018543645409317 .
epoch 15 complete with accuracy 0.9008367254635912 .
epoch 16 complete with accuracy 0.900497512437811 .
epoch 17 complete with accuracy 0.9028720036182722 .
epoch 18 complete with accuracy 0.9023066485753053 .
epoc

(array([ 0.05100364, -0.04003548, -0.04820169,  0.00348697,  0.09597629,
         0.24426895,  0.1397415 ,  0.14166851,  0.00927319, -0.03068248,
         0.09833885, -0.01288033,  0.00663194,  0.20319438,  0.03675985,
         0.16440735,  0.01863277, -0.03202437, -0.12623664,  0.0242156 ,
         0.01958675, -0.0095158 , -0.03058063, -0.11956963, -0.01875051,
        -0.0236975 , -0.03408019,  0.08915817,  0.0729306 ,  0.04062483]),
 0.21887969814974456)

In [5]:
PhishingDynamicPerceptron = DynamicPerceptron(num_features, epochs=100)
DynamicWeights = PhishingDynamicPerceptron.train(train_data, train_labels)[0]

epoch 0 complete with accuracy 0.8974445952057892 .
epoch 1 complete with accuracy 0.9062641338760742 .
epoch 2 complete with accuracy 0.9054726368159204 .
epoch 3 complete with accuracy 0.9035504296698327 .
epoch 4 complete with accuracy 0.9049072817729534 .
epoch 5 complete with accuracy 0.9016282225237449 .
epoch 6 complete with accuracy 0.9018543645409317 .
epoch 7 complete with accuracy 0.9032112166440525 .
epoch 8 complete with accuracy 0.9020805065581184 .
epoch 9 complete with accuracy 0.9029850746268657 .
epoch 10 complete with accuracy 0.9015151515151515 .
epoch 11 complete with accuracy 0.9028720036182722 .
epoch 12 complete with accuracy 0.9023066485753053 .
epoch 13 complete with accuracy 0.9029850746268657 .
epoch 14 complete with accuracy 0.9024197195838987 .
epoch 15 complete with accuracy 0.9035504296698327 .
epoch 16 complete with accuracy 0.9015151515151515 .
epoch 17 complete with accuracy 0.9015151515151515 .
epoch 18 complete with accuracy 0.9011759384893713 .
epo

(array([ 8.68858063e-04, -4.83531550e-05, -8.88564844e-04,  5.12505749e-05,
         1.65834198e-03,  1.27952734e-01,  1.93287614e-03,  1.95460020e-03,
        -4.61074871e-04, -5.17775326e-04,  2.00605781e-03, -2.71664678e-04,
         3.86873262e-05,  3.36376516e-03,  7.55399088e-04,  2.74219796e-03,
         1.20298138e-05, -2.18374206e-04, -1.65627209e-03,  8.53104969e-04,
         6.19942238e-04, -4.91622179e-04, -3.00246299e-04, -1.76579323e-03,
        -8.93849615e-05, -1.58717306e-03, -5.15538837e-04,  1.36234019e-03,
         1.11267744e-03,  8.08165280e-04]), 0.12739810844121605)

In [6]:
PhishingMarginPerceptron = MarginPerceptron(num_features, epochs=100)
MarginWeights = PhishingMarginPerceptron.train(train_data, train_labels)[0]

epoch 0 complete with accuracy 0.8925825418362732 .
epoch 1 complete with accuracy 0.8990275893260968 .
epoch 2 complete with accuracy 0.8952962460425147 .
epoch 3 complete with accuracy 0.891677973767526 .
epoch 4 complete with accuracy 0.8878335594753505 .
epoch 5 complete with accuracy 0.8867028493894166 .
epoch 6 complete with accuracy 0.8831976481230213 .
epoch 7 complete with accuracy 0.8813885119855269 .
epoch 8 complete with accuracy 0.8816146540027137 .
epoch 9 complete with accuracy 0.8784486657620986 .
epoch 10 complete with accuracy 0.8749434644957033 .
epoch 11 complete with accuracy 0.8747173224785165 .
epoch 12 complete with accuracy 0.8712121212121212 .
epoch 13 complete with accuracy 0.8715513342379014 .
epoch 14 complete with accuracy 0.8705336951605608 .
epoch 15 complete with accuracy 0.8696291270918136 .
epoch 16 complete with accuracy 0.8672546359113523 .
epoch 17 complete with accuracy 0.8662369968340118 .
epoch 18 complete with accuracy 0.8662369968340118 .
epoc

(array([ 0.03315661, -0.00773735, -0.04355669,  0.00303571,  0.04787782,
         0.14616553,  0.07316817,  0.07165083, -0.01807231, -0.03084748,
         0.07350203, -0.0187202 ,  0.03021387,  0.13363333,  0.01826159,
         0.0954375 , -0.00794987, -0.02492693, -0.07379753,  0.02133958,
         0.03409109, -0.00985789, -0.02290126, -0.03487195, -0.00419377,
        -0.0353714 , -0.02250431,  0.05768555,  0.03939844,  0.02254438]),
 0.13410550456040235)

In [7]:
PhishingAveragedPerceptron = AveragedPerceptron(num_features, epochs=100)
AveragedWeights = PhishingAveragedPerceptron.train(train_data, train_labels)[0]

epoch 0 complete with accuracy 0.8986883763003166 .
epoch 1 complete with accuracy 0.9006105834464043 .
epoch 2 complete with accuracy 0.9001582994120307 .
epoch 3 complete with accuracy 0.904228855721393 .
epoch 4 complete with accuracy 0.9029850746268657 .
epoch 5 complete with accuracy 0.9006105834464043 .
epoch 6 complete with accuracy 0.9011759384893713 .
epoch 7 complete with accuracy 0.9006105834464043 .
epoch 8 complete with accuracy 0.9003844414292176 .
epoch 9 complete with accuracy 0.9017412935323383 .
epoch 10 complete with accuracy 0.8992537313432836 .
epoch 11 complete with accuracy 0.9024197195838987 .
epoch 12 complete with accuracy 0.905359565807327 .
epoch 13 complete with accuracy 0.8972184531886025 .
epoch 14 complete with accuracy 0.9006105834464043 .
epoch 15 complete with accuracy 0.9011759384893713 .
epoch 16 complete with accuracy 0.9027589326096789 .
epoch 17 complete with accuracy 0.9015151515151515 .
epoch 18 complete with accuracy 0.9014020805065581 .
epoch

(array([ 0.06568916, -0.00141234, -0.06350818, -0.01080629,  0.11209992,
         0.30818247,  0.14312393,  0.15540968, -0.01701253, -0.05326739,
         0.12094767,  0.00181108,  0.03473508,  0.23440889,  0.04766331,
         0.15858254,  0.00031273, -0.04096317, -0.1182348 ,  0.06710547,
         0.05023475, -0.01526232, -0.02279409, -0.08852693,  0.00121398,
        -0.05855387, -0.04231425,  0.09649582,  0.05931794,  0.06753256]),
 0.28590207499173875)

In [8]:
PhishingAggressiveMarginPerceptron = AggressiveMarginPerceptron(num_features, epochs=100)
AggressiveMarginWeights = PhishingAggressiveMarginPerceptron.train(train_data, train_labels)[0]

epoch 0 complete with accuracy 0.7894617819990954 .
epoch 1 complete with accuracy 0.8005427408412483 .
epoch 2 complete with accuracy 0.8002035278154681 .
epoch 3 complete with accuracy 0.8002035278154681 .
epoch 4 complete with accuracy 0.8000904568068747 .
epoch 5 complete with accuracy 0.8000904568068747 .
epoch 6 complete with accuracy 0.8006558118498417 .
epoch 7 complete with accuracy 0.8005427408412483 .
epoch 8 complete with accuracy 0.8008819538670285 .
epoch 9 complete with accuracy 0.8007688828584351 .
epoch 10 complete with accuracy 0.8008819538670285 .
epoch 11 complete with accuracy 0.8008819538670285 .
epoch 12 complete with accuracy 0.8008819538670285 .
epoch 13 complete with accuracy 0.8007688828584351 .
epoch 14 complete with accuracy 0.8006558118498417 .
epoch 15 complete with accuracy 0.8007688828584351 .
epoch 16 complete with accuracy 0.8006558118498417 .
epoch 17 complete with accuracy 0.8007688828584351 .
epoch 18 complete with accuracy 0.8008819538670285 .
epo

(array([ 0.00143239, -0.00153116, -0.00271604, -0.00084765,  0.00783272,
         0.02511749,  0.01031835,  0.01074446, -0.00019995, -0.0044578 ,
         0.00959665, -0.00207297, -0.00046907,  0.01270245,  0.00426921,
         0.01180933,  0.00018394, -0.00256805, -0.00735271,  0.00222634,
         0.00417146, -0.00117081, -0.00163308, -0.00570809, -0.00121791,
        -0.0047083 , -0.00159644,  0.00640038,  0.0036271 ,  0.00393107]),
 0.021244235540371345)

In [9]:
PhishingSimplePerceptron.test(test_data, test_labels)
PhishingDynamicPerceptron.test(test_data, test_labels)
PhishingMarginPerceptron.test(test_data, test_labels)
PhishingAveragedPerceptron.test(test_data, test_labels)
PhishingAggressiveMarginPerceptron.test(test_data, test_labels)



accuracy on test set is 0.9232926277702397 .
accuracy on test set is 0.917774762550882 .
accuracy on test set is 0.9227498869289914 .
accuracy on test set is 0.9200361827227499 .
accuracy on test set is 0.9178652193577567 .


0.9178652193577567